### ISSUE TITLE
Waymarks are not displayed correctly

### ISSUE THREAD

**Issue by Akurosia** [PunishedPineapple/WaymarkLibrarian#2]
I tried this tool yesterday.

Preset 2-5 correspond to waymarks for e5s-e8s and were recreated yesterday as well (to make sure they are up to date)
Neither the Zone name nore the marker information (including timestamp) are displayed correct.

Is there a file you need to have a look into?

**Comment by PunishedPineapple** [comment]
It's pretty interesting that your file is the same size as expected so as not to trigger a warning, but is storing data differently and causing that.  Which game language are you using?  I wonder if different client languages use different locations in the file.

I'd like to see your UISAVE.DAT for any character that has saved presets and sees that issue, but that file also does contain your sent mail history, recent contacts list, and what appears to be a copy of friends list and blacklist, so I'm not sure if you'd be comfortable sharing it, or if GitHub provides a way to privately share files (if you'd even trust me with it).

Another option, if sharing the file isn't something you are willing to do, would be for you to create a backup of the UISAVE.DAT file for a character, change the first and last waymark presets on that character in-game, and diff the files to see where it changed.  Then you could send me the data from the first change to the last change, and the offset in the file of the first change so I could see if it's moved or if the format is different.  The first 64 or so bytes of the file would also be useful to see if there's some kind of flag in the header that could be used.

Also, you may want to black out your CHR that's shown in the preset name that's in the library pane.  That's the Content ID for that character, and Idk enough to know if anyone can abuse that or not.

**Comment by PunishedPineapple** [comment]
I tried running the German client and saving waymarks, and the program reads it fine.  Both overwriting the existing UISAVE and deleting it to force a fresh write put the waymark data in the expected location in the file.  I'm definitely interested to see where/how it's stored in your file.

I'll try checking with the JP and FR clients too just to be certain, but that's going to be harder for me to do.

**Comment by Akurosia** [comment]
i use the German client (with german windows 10)

**Comment by PunishedPineapple** [comment]
I've tried all of the client langauges and not had any problems, so if you can provide a UISAVE.DAT that causes this issue or the data from it mentioned above, it would help.  If not, I'll try setting up a German Windows 10 VM later in the week and checking.  I can't imagine it would be, but if it's OS version dependent, that's going to be a really frustrating problem to solve...

**Comment by Akurosia** [comment]
Here is my UISAVE.DAT

[UISAVE.zip](https://github.com/PunishedPineapple/WaymarkLibrarian/files/4872894/UISAVE.zip)

**Comment by PunishedPineapple** [comment]
Thank you.

The waymark data is located an additional 19 bytes further in to your file than mine.  There appears to be a byte showing that offset at 0x6C63, but I guess I need to try to get a better understanding of the file format to really know how to fix this properly.

**Comment by PunishedPineapple** [comment]
Should be fixed with the latest release.  Tested ok with your file.
