### ISSUE TITLE
Zone Number Addition

### ISSUE THREAD

**Issue by TheyCallMeZ** [PunishedPineapple/WaymarkLibrarian#4]
Zone #782 = The Cloud Deck (Extreme)

Also known as Diamond Weapon Extreme

**Comment by PunishedPineapple** [comment]
Sorry, I forgot to update the zone list for 5.5.  The new list is live now, so it'll either prompt your for an update a day after the last time it checked, or you can set the last update check time back a day in `%AppData%\PunishedPineapple\WaymarkLibrarian\Options.cfg` to have it check again on the next launch.
